site_name: Parboil Documentation
site_author: J. Neugebauer
site_description: Quickly generate files and projects from common templates.
repo_url: https://github.com/jneug/parboil
repo_name: jneug/parboil

theme:
    name: material
    features:
        - content.code.annotate
        - navigation.top
        - navigation.tracking
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode

nav:
    - Introduction: index.md
    - Overview: overview.md
    - Writing Recipes:
          - Quick start: recipes/quickstart.md
          - How to write recipes: recipes/howto.md
          - Ingredients: recipes/ingredients.md
          - Advanced recipes: recipes/advanced.md
    - Commandline Interface: cli.md
    - Reference:
          - recipes: reference/recipes.md
          - renderer: reference/renderer.md

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
    - mkdocs-click
    - pymdownx.magiclink
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.smartsymbols
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - search
    - autorefs
    - mkdocstrings:
          watch:
              - src
          handlers:
              python:
                  import:
                      - https://rich.readthedocs.io/en/stable/objects.inv
                      # - https://jinja.palletsprojects.com/en/3.1.x/objects.inv
